name: Tests
# on: push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  workflows:
    strategy:
      matrix:
        platform: [ubuntu-latest] #, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install modules
        run: yarn
      - name: Deploy Contract
        run: printf 'y\n' | yarn deploy
      - name: Run tests
        run: yarn test
